#!/usr/bin/env python3
"""Generate the aumm-app M1 ABI package from committed forge artifacts.

PB-D74 (v). The roster is the fifteen-artifact M1 read surface derived from
aumm-app PLAN section 4; every entry resolves under the default profile into
out/, the Vault included, whose bindable surface is the composed IVault
interface rather than the concrete out-vault/ artifact per PB-D74 (ii).

Emits under --out: one TypeScript module per roster entry exporting the ABI as
a const assertion, an index.ts barrel, and PROVENANCE.json. Every emitted ABI
is a verbatim copy of the abi array in the artifact named beside it, so the
audit is a regenerate-and-diff.
"""

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

# Package name -> artifact path, relative to the repo root. Fourteen rows are
# identity mappings from the contract's own artifact. The Vault row is not, and
# the reason is load-bearing per PB-D74 (ii): getPoolTokens,
# getStaticSwapFeePercentage and isPoolInitialized all live on IVaultExtension
# and reach the Vault through fallback delegation, so the concrete
# out-vault/Vault.sol/Vault.json ABI alone would fail every pool read.
ROSTER = {
    "AuMM": "out/AuMM.sol/AuMM.json",
    "AureumGovernance": "out/AureumGovernance.sol/AureumGovernance.json",
    "BodenseeBootstrapChannel": "out/BodenseeBootstrapChannel.sol/BodenseeBootstrapChannel.json",
    "CCBMultiplier": "out/CCBMultiplier.sol/CCBMultiplier.json",
    "EMASampler": "out/EMASampler.sol/EMASampler.json",
    "EfficiencyOracle": "out/EfficiencyOracle.sol/EfficiencyOracle.json",
    "EmissionDistributor": "out/EmissionDistributor.sol/EmissionDistributor.json",
    "GaugeEligibility": "out/GaugeEligibility.sol/GaugeEligibility.json",
    "GaugeRegistry": "out/GaugeRegistry.sol/GaugeRegistry.json",
    "IERC4626": "out/IERC4626.sol/IERC4626.json",
    "MiliariumRegistry": "out/MiliariumRegistry.sol/MiliariumRegistry.json",
    "Router": "out/Router.sol/Router.json",
    "TVLOracle": "out/TVLOracle.sol/TVLOracle.json",
    "Vault": "out/IVault.sol/IVault.json",
    "VotingWeight": "out/VotingWeight.sol/VotingWeight.json",
    "WeightedPool": "out/WeightedPool.sol/WeightedPool.json",
}

EXPECTED_ROSTER_SIZE = 16

# PB-D74 (iii). No out-vault/ artifact ships, so this records the fact the
# provenance requirement exists to preserve rather than leaving it unstated.
VAULT_PROFILE_NOTE = (
    "The deployed Vault, VaultAdmin and VaultExtension build under "
    "[profile.vault] into out-vault/ at solc 0.8.30, while every artifact in "
    "this package builds under the default profile into out/ at solc 0.8.26. "
    "An ABI is source-shape-determined rather than compiler-determined, so the "
    "IVault interface artifact shipped here under the name Vault describes the "
    "deployed implementation exactly. RB-018 records the build-order trap."
)

GENERATOR = "tools/generate_abi_package.py"


def fail(message):
    raise SystemExit(f"generate_abi_package: {message}")


def load_artifact(root, rel):
    path = root / rel
    if not path.is_file():
        fail(f"artifact not found: {rel} (run forge build first)")
    artifact = json.loads(path.read_text(encoding="utf-8"))
    abi = artifact.get("abi")
    if not isinstance(abi, list) or not abi:
        fail(f"artifact carries no abi array: {rel}")
    return artifact


def compilation_target(artifact, rel):
    metadata = artifact.get("metadata") or {}
    targets = (metadata.get("settings") or {}).get("compilationTarget") or {}
    if len(targets) != 1:
        fail(f"expected one compilationTarget in {rel}, got {len(targets)}")
    return next(iter(targets))


def solc_version(artifact, rel):
    metadata = artifact.get("metadata") or {}
    version = (metadata.get("compiler") or {}).get("version")
    if not version:
        fail(f"no compiler version in {rel}")
    return version


def git_state(root):
    def run(args):
        result = subprocess.run(args, cwd=root, capture_output=True, text=True)
        if result.returncode != 0:
            fail(f"git {args[1]} failed: {result.stderr.strip()}")
        return result.stdout.strip()

    return run(["git", "rev-parse", "HEAD"]), bool(run(["git", "status", "--porcelain"]))


def emit_module(out_dir, name, rel, abi):
    lines = [
        f"// Generated by {GENERATOR} from {rel}. Do not edit by hand.",
        "",
        f"export const {name}Abi = {json.dumps(abi, indent=2)} as const;",
        "",
    ]
    (out_dir / f"{name}.ts").write_text("\n".join(lines), encoding="utf-8")


def emit_barrel(out_dir, names):
    lines = [f"// Generated by {GENERATOR}. Do not edit by hand.", ""]
    lines += [f'export {{ {name}Abi }} from "./{name}";' for name in names]
    lines.append("")
    (out_dir / "index.ts").write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Generate the aumm-app M1 ABI package.")
    parser.add_argument("--out", required=True, help="target directory, e.g. ../aumm-app/src/abi")
    args = parser.parse_args()

    if len(ROSTER) != EXPECTED_ROSTER_SIZE:
        fail(f"roster is {len(ROSTER)} entries, expected {EXPECTED_ROSTER_SIZE}")

    root = Path(__file__).resolve().parent.parent
    out_dir = Path(args.out).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    commit, dirty = git_state(root)
    artifacts = {}
    names = sorted(ROSTER)

    for name in names:
        rel = ROSTER[name]
        artifact = load_artifact(root, rel)
        abi = artifact["abi"]
        emit_module(out_dir, name, rel, abi)
        canonical = json.dumps(abi, sort_keys=True, separators=(",", ":"))
        artifacts[name] = {
            "source": compilation_target(artifact, rel),
            "artifact": rel,
            "profile": "default",
            "solc": solc_version(artifact, rel),
            "abiSha256": hashlib.sha256(canonical.encode("utf-8")).hexdigest(),
            "entries": len(abi),
        }

    emit_barrel(out_dir, names)

    provenance = {
        "generator": GENERATOR,
        "sourceRepo": "aumm-deploy",
        "commit": commit,
        "dirty": dirty,
        "vaultProfileNote": VAULT_PROFILE_NOTE,
        "artifacts": artifacts,
    }
    with (out_dir / "PROVENANCE.json").open("w", encoding="utf-8") as handle:
        json.dump(provenance, handle, indent=2, sort_keys=True)
        handle.write("\n")

    print(f"wrote {len(names)} ABI modules + index.ts + PROVENANCE.json to {out_dir}")
    if dirty:
        print("WARNING: working tree dirty; the recorded commit does not fully describe this package")
    return 0


if __name__ == "__main__":
    sys.exit(main())
